### ISSUE TITLE
Error `UserRejectedRequestError` thrown on subsequent Braavos wallet connection

### ISSUE THREAD

**Issue by wa0x6e** [argentlabs/starknetkit#140]
Seems like there's an issue when connecting to a previously connected Braavos wallet.

On the first connection, it's correctly opening the argent X modal (asking to choose wallet), and choosing Braavos successfully connect to the Braavos wallet. But after disconnecting, reconnecting again is throwing the error `UserRejectedRequestError`. (this does not happen with the other connectors)

Simple app for reproduction: https://github.com/wa0x6e/starknetkit-test

- Clone the repo
- `yarn install`
- `yarn dev`
- Open http://localhost:5173/
- Open the browser dev console
- Click on the "Connect" button
- Choose argent X
- it connects
- Click on "Disconnect"
- it disconnects
- You can connect and disconnect as many time with argent X connector without errors
- Trying to do the same with Braavos will only work on first connection and disconnection, any subsequent connection is throwing the `UserRejectedRequestError` error

**Comment by Generalresolution03** [comment]
@wa0x6e 
have you find a way around this issue?

**Comment by wa0x6e** [comment]
> @wa0x6e have you find a way around this issue?

No, this is preventing us from upgrading to starknetkit v2

**Comment by bluecco** [comment]
@wa0x6e I've tried to replicate on our test dapp first, but couldn't replicate https://dapp-argentlabs.vercel.app

I've cloned your repo and these are the result
- argentX working fine as you said
- braavos: working with first connect or page refresh
    - not working after disconnect (same as you)


on first connect (or page refresh) everything is correctly handled in braavos in their switch case

```typescript
switch ((0, _classPrivateFieldLooseBase2.default)(this, _snjsVersion)[_snjsVersion]) // returns v6
case "v6":
   switch (call.type) {
    ...
     case "wallet_requestAccounts": 
        // handle
```

<img width="438" alt="image" src="https://github.com/user-attachments/assets/d6c2f11f-fc45-449a-988c-e3df1fd4829c">


after calling disconnect and trying to connect again, it seems braavos has `v5` as snjsVersion (starknetkit only uses v6.11.0)

<img width="815" alt="image" src="https://github.com/user-attachments/assets/412c1802-7dfe-48f6-a804-524b0e5720ee">


resulting in `not implemented`

<img width="586" alt="image" src="https://github.com/user-attachments/assets/2027753d-6bfc-4c31-8dd2-d044bba3f103">


it would be better to reach out to them (for a better support / debug on braavos side)
