### ISSUE TITLE
Expected valid bigint: 0 < bigint < curve.n

### ISSUE THREAD

**Issue by kseikyo** [argentlabs/starknetkit#159]
Related issue on [starknet-react repo](https://github.com/apibara/starknet-react/issues/510)

This issue was introduced in the commit ([5fae298](https://github.com/argentlabs/starknetkit/commit/5fae2982ed321c911ed502245ec7f601dcc7531e)) and it's related to `account.execute()` calls.

I've tested by installing starknetkit@2.3.0 and using the latest @starknet-react/core@3.6.0 with the same code from the original issue, which works as expected, and after upgrading starknetkit to 2.3.1 I get the same error `Expected valid bigint: 0 < bigint < curve.n`.

**Comment by bluecco** [comment]
@kseikyo that's unfortunately an issue related to starknetjs (we're already in talking to fix it)

at the moment, you should use this hook instead of directly calling `account.execute`
https://www.starknet-react.com/docs/hooks/use-wallet-request

**Comment by kseikyo** [comment]
Thanks for the speedy reply!

We're using `account.execute` to invoke transactions with `contract.populateTransaction`, so I guess we have to move from it and only use `useSendTransaction` from now on.

**Comment by bluecco** [comment]
when using `starknet-react` I would suggest to always use their hooks
as soon as starknetjs will be updated, we'll also update our `get account` method to return a `WalletAccount`
but this could take a while

closing the issue for now
