### ISSUE TITLE
ConnectorNotConnectedError: Connector not connected

### ISSUE THREAD

**Issue by EvanYan1024** [argentlabs/starknetkit#45]
When I didn’t install a Starknet wallet, I encountered an error when using connect.
<img width="567" alt="image" src="https://github.com/argentlabs/starknetkit/assets/136288110/d8947394-55d2-4870-959d-4ecee2080a20">
<img width="363" alt="image" src="https://github.com/argentlabs/starknetkit/assets/136288110/95ac2df6-de88-49d2-a310-4b4c49dc7757">
It appears in this method mapModalWallets, it reads the name field, but get name throws an error

**Comment by bluecco** [comment]
hi @EvanYan1024, what do you mean by `When I didn’t install a Starknet wallet`?

could you give some more details to understand the issue and how to reproduce?

**Comment by EvanYan1024** [comment]
@bluecco, hello，This means that when my browser does not have the argentX and braavos extensions installed, for example, you can open the page in incognito mode, and this error will appear.

**Comment by bluecco** [comment]
@EvanYan1024 I've tried to replicate with my local dapp, but I cannot achieve the same error

https://github.com/argentlabs/starknetkit/assets/7635032/601abfdb-23a1-4a9a-afc8-e982feea2499

Could you share:
- the starknetkit version you're using 
- code (or the snippet) that implements starknetkit?

**Comment by EvanYan1024** [comment]
@bluecco Thanks for your reply, you can try edge browser，
I guess this is the reason, you can check out my PR。
https://github.com/starknet-io/get-starknet/pull/207/files

**Comment by bluecco** [comment]
@EvanYan1024 sorry for the delay, we're still waiting for the linked pr to be merged (and then update get-starknet react here)

**Comment by YanYuanFE** [comment]
@bluecco Thanks for your reply. It seems that the get-starknet library is no longer updated.

**Comment by lazarmitic** [comment]
We also have same issue in our dApp on Edge browser, is there a workaround, or we need to wait for get-starknet to merge above PR? Can we replace `getDiscoveryWallets()` from starknet-core with our own version and put it in starknet-kit?

**Comment by YanYuanFE** [comment]
@lazarmitic ，hi，you can use patch package to fix get-starknet,
https://www.npmjs.com/package/patch-package

**Comment by TEMHITHORPHE** [comment]
> @bluecco Thanks for your reply, you can try edge browser， I guess this is the reason, you can check out my PR。 https://github.com/starknet-io/get-starknet/pull/207/files

This has been merged now, any updates ?

**Comment by bluecco** [comment]
will need this pr to be merged first 

https://github.com/starknet-io/get-starknet/pull/238

otherwise, current implementation will break ssr (ie: using nextjs)

**Comment by arentant** [comment]
> @TEMHITHORPHE pr is opened, should be merged tomorrow (after internal testing) #97

Hi, any updates?

**Comment by bluecco** [comment]
@arentant the pr on get-starknet is merged but not released
checking with starknetjs team

**Comment by bluecco** [comment]
it will be published after the merge of https://github.com/starknet-io/get-starknet/pull/244

**Comment by bluecco** [comment]
an update on this issue: we released starknetkit@2.3.2 (can be installed with `@latest` tag)
this version has few small breaking changes (docs updated here: https://www.starknetkit.com/docs/latest/getting-started)

it uses the latest version of get-starknet that also includes edge
