### ISSUE TITLE
Issue connecting with Argent Web and Mobile wallets

### ISSUE THREAD

**Issue by nenadV91** [argentlabs/starknetkit#63]
Hello,

I've noticed that sometimes there are issues connecting with
- Argent Web wallet
- Argent Mobile wallet

These issues can be seen here:
https://app.ekubo.org/
https://app.avnu.fi/

Hope this is resolved soon.

**Comment by bluecco** [comment]
Hi @nenadV91,

we updated starknetkit since then and both ekubo and avnu should have already updated it

checked today with both dapps, no problems with mobile and webwallet

let me know if you can connect too and we'll take another look at the issue

**Comment by nenadV91** [comment]
@bluecco Thank you sir 🙏
